// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: project/project_service.proto

package project

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_project_project_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_project_project_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListProjectsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProjectsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_project_project_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_project_project_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ListProjectsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_project_project_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_project_project_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectResponse) Reset() {
	*x = GetProjectResponse{}
	mi := &file_project_project_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectResponse) ProtoMessage() {}

func (x *GetProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectResponse.ProtoReflect.Descriptor instead.
func (*GetProjectResponse) Descriptor() ([]byte, []int) {
	return file_project_project_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Architecture  string                 `protobuf:"bytes,5,opt,name=architecture,proto3" json:"architecture,omitempty"`
	RepositoryUrl string                 `protobuf:"bytes,6,opt,name=repository_url,json=repositoryUrl,proto3" json:"repository_url,omitempty"`
	DemoUrl       string                 `protobuf:"bytes,7,opt,name=demo_url,json=demoUrl,proto3" json:"demo_url,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,8,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Featured      bool                   `protobuf:"varint,9,opt,name=featured,proto3" json:"featured,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	GithubStars   int32                  `protobuf:"varint,11,opt,name=github_stars,json=githubStars,proto3" json:"github_stars,omitempty"`
	ReadTime      int32                  `protobuf:"varint,12,opt,name=read_time,json=readTime,proto3" json:"read_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_project_project_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_project_project_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProjectRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateProjectRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateProjectRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProjectRequest) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *CreateProjectRequest) GetRepositoryUrl() string {
	if x != nil {
		return x.RepositoryUrl
	}
	return ""
}

func (x *CreateProjectRequest) GetDemoUrl() string {
	if x != nil {
		return x.DemoUrl
	}
	return ""
}

func (x *CreateProjectRequest) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *CreateProjectRequest) GetFeatured() bool {
	if x != nil {
		return x.Featured
	}
	return false
}

func (x *CreateProjectRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateProjectRequest) GetGithubStars() int32 {
	if x != nil {
		return x.GithubStars
	}
	return 0
}

func (x *CreateProjectRequest) GetReadTime() int32 {
	if x != nil {
		return x.ReadTime
	}
	return 0
}

type CreateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectResponse) Reset() {
	*x = CreateProjectResponse{}
	mi := &file_project_project_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectResponse) ProtoMessage() {}

func (x *CreateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return file_project_project_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type UpdateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Architecture  string                 `protobuf:"bytes,6,opt,name=architecture,proto3" json:"architecture,omitempty"`
	RepositoryUrl string                 `protobuf:"bytes,7,opt,name=repository_url,json=repositoryUrl,proto3" json:"repository_url,omitempty"`
	DemoUrl       string                 `protobuf:"bytes,8,opt,name=demo_url,json=demoUrl,proto3" json:"demo_url,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,9,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Featured      bool                   `protobuf:"varint,10,opt,name=featured,proto3" json:"featured,omitempty"`
	Status        string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	GithubStars   int32                  `protobuf:"varint,12,opt,name=github_stars,json=githubStars,proto3" json:"github_stars,omitempty"`
	ReadTime      int32                  `protobuf:"varint,13,opt,name=read_time,json=readTime,proto3" json:"read_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_project_project_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_project_project_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProjectRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpdateProjectRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateProjectRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *UpdateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProjectRequest) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *UpdateProjectRequest) GetRepositoryUrl() string {
	if x != nil {
		return x.RepositoryUrl
	}
	return ""
}

func (x *UpdateProjectRequest) GetDemoUrl() string {
	if x != nil {
		return x.DemoUrl
	}
	return ""
}

func (x *UpdateProjectRequest) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *UpdateProjectRequest) GetFeatured() bool {
	if x != nil {
		return x.Featured
	}
	return false
}

func (x *UpdateProjectRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateProjectRequest) GetGithubStars() int32 {
	if x != nil {
		return x.GithubStars
	}
	return 0
}

func (x *UpdateProjectRequest) GetReadTime() int32 {
	if x != nil {
		return x.ReadTime
	}
	return 0
}

type UpdateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectResponse) Reset() {
	*x = UpdateProjectResponse{}
	mi := &file_project_project_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectResponse) ProtoMessage() {}

func (x *UpdateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectResponse.ProtoReflect.Descriptor instead.
func (*UpdateProjectResponse) Descriptor() ([]byte, []int) {
	return file_project_project_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type DeleteProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_project_project_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_project_project_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectResponse) Reset() {
	*x = DeleteProjectResponse{}
	mi := &file_project_project_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectResponse) ProtoMessage() {}

func (x *DeleteProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteProjectResponse) Descriptor() ([]byte, []int) {
	return file_project_project_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteProjectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_project_project_service_proto protoreflect.FileDescriptor

const file_project_project_service_proto_rawDesc = "" +
	"\n" +
	"\x1dproject/project_service.proto\x12\aproject\x1a\x15project/project.proto\"?\n" +
	"\x13ListProjectsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"Z\n" +
	"\x14ListProjectsResponse\x12,\n" +
	"\bprojects\x18\x01 \x03(\v2\x10.project.ProjectR\bprojects\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"#\n" +
	"\x11GetProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x12GetProjectResponse\x12*\n" +
	"\aproject\x18\x01 \x01(\v2\x10.project.ProjectR\aproject\"\xf4\x02\n" +
	"\x14CreateProjectRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\"\n" +
	"\farchitecture\x18\x05 \x01(\tR\farchitecture\x12%\n" +
	"\x0erepository_url\x18\x06 \x01(\tR\rrepositoryUrl\x12\x19\n" +
	"\bdemo_url\x18\a \x01(\tR\ademoUrl\x12\x1c\n" +
	"\tthumbnail\x18\b \x01(\tR\tthumbnail\x12\x1a\n" +
	"\bfeatured\x18\t \x01(\bR\bfeatured\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12!\n" +
	"\fgithub_stars\x18\v \x01(\x05R\vgithubStars\x12\x1b\n" +
	"\tread_time\x18\f \x01(\x05R\breadTime\"C\n" +
	"\x15CreateProjectResponse\x12*\n" +
	"\aproject\x18\x01 \x01(\v2\x10.project.ProjectR\aproject\"\x84\x03\n" +
	"\x14UpdateProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\"\n" +
	"\farchitecture\x18\x06 \x01(\tR\farchitecture\x12%\n" +
	"\x0erepository_url\x18\a \x01(\tR\rrepositoryUrl\x12\x19\n" +
	"\bdemo_url\x18\b \x01(\tR\ademoUrl\x12\x1c\n" +
	"\tthumbnail\x18\t \x01(\tR\tthumbnail\x12\x1a\n" +
	"\bfeatured\x18\n" +
	" \x01(\bR\bfeatured\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12!\n" +
	"\fgithub_stars\x18\f \x01(\x05R\vgithubStars\x12\x1b\n" +
	"\tread_time\x18\r \x01(\x05R\breadTime\"C\n" +
	"\x15UpdateProjectResponse\x12*\n" +
	"\aproject\x18\x01 \x01(\v2\x10.project.ProjectR\aproject\"&\n" +
	"\x14DeleteProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteProjectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x94\x03\n" +
	"\x0eProjectService\x12K\n" +
	"\fListProjects\x12\x1c.project.ListProjectsRequest\x1a\x1d.project.ListProjectsResponse\x12E\n" +
	"\n" +
	"GetProject\x12\x1a.project.GetProjectRequest\x1a\x1b.project.GetProjectResponse\x12N\n" +
	"\rCreateProject\x12\x1d.project.CreateProjectRequest\x1a\x1e.project.CreateProjectResponse\x12N\n" +
	"\rUpdateProject\x12\x1d.project.UpdateProjectRequest\x1a\x1e.project.UpdateProjectResponse\x12N\n" +
	"\rDeleteProject\x12\x1d.project.DeleteProjectRequest\x1a\x1e.project.DeleteProjectResponseB\x1cZ\x1aportfolio-ai/proto/projectb\x06proto3"

var (
	file_project_project_service_proto_rawDescOnce sync.Once
	file_project_project_service_proto_rawDescData []byte
)

func file_project_project_service_proto_rawDescGZIP() []byte {
	file_project_project_service_proto_rawDescOnce.Do(func() {
		file_project_project_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_project_project_service_proto_rawDesc), len(file_project_project_service_proto_rawDesc)))
	})
	return file_project_project_service_proto_rawDescData
}

var file_project_project_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_project_project_service_proto_goTypes = []any{
	(*ListProjectsRequest)(nil),   // 0: project.ListProjectsRequest
	(*ListProjectsResponse)(nil),  // 1: project.ListProjectsResponse
	(*GetProjectRequest)(nil),     // 2: project.GetProjectRequest
	(*GetProjectResponse)(nil),    // 3: project.GetProjectResponse
	(*CreateProjectRequest)(nil),  // 4: project.CreateProjectRequest
	(*CreateProjectResponse)(nil), // 5: project.CreateProjectResponse
	(*UpdateProjectRequest)(nil),  // 6: project.UpdateProjectRequest
	(*UpdateProjectResponse)(nil), // 7: project.UpdateProjectResponse
	(*DeleteProjectRequest)(nil),  // 8: project.DeleteProjectRequest
	(*DeleteProjectResponse)(nil), // 9: project.DeleteProjectResponse
	(*Project)(nil),               // 10: project.Project
}
var file_project_project_service_proto_depIdxs = []int32{
	10, // 0: project.ListProjectsResponse.projects:type_name -> project.Project
	10, // 1: project.GetProjectResponse.project:type_name -> project.Project
	10, // 2: project.CreateProjectResponse.project:type_name -> project.Project
	10, // 3: project.UpdateProjectResponse.project:type_name -> project.Project
	0,  // 4: project.ProjectService.ListProjects:input_type -> project.ListProjectsRequest
	2,  // 5: project.ProjectService.GetProject:input_type -> project.GetProjectRequest
	4,  // 6: project.ProjectService.CreateProject:input_type -> project.CreateProjectRequest
	6,  // 7: project.ProjectService.UpdateProject:input_type -> project.UpdateProjectRequest
	8,  // 8: project.ProjectService.DeleteProject:input_type -> project.DeleteProjectRequest
	1,  // 9: project.ProjectService.ListProjects:output_type -> project.ListProjectsResponse
	3,  // 10: project.ProjectService.GetProject:output_type -> project.GetProjectResponse
	5,  // 11: project.ProjectService.CreateProject:output_type -> project.CreateProjectResponse
	7,  // 12: project.ProjectService.UpdateProject:output_type -> project.UpdateProjectResponse
	9,  // 13: project.ProjectService.DeleteProject:output_type -> project.DeleteProjectResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_project_project_service_proto_init() }
func file_project_project_service_proto_init() {
	if File_project_project_service_proto != nil {
		return
	}
	file_project_project_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_project_project_service_proto_rawDesc), len(file_project_project_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_project_project_service_proto_goTypes,
		DependencyIndexes: file_project_project_service_proto_depIdxs,
		MessageInfos:      file_project_project_service_proto_msgTypes,
	}.Build()
	File_project_project_service_proto = out.File
	file_project_project_service_proto_goTypes = nil
	file_project_project_service_proto_depIdxs = nil
}
