// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: project/project.proto

package project

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Project struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug             string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Summary          string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Description      string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Architecture     string                 `protobuf:"bytes,6,opt,name=architecture,proto3" json:"architecture,omitempty"`
	RepositoryUrl    string                 `protobuf:"bytes,7,opt,name=repository_url,json=repositoryUrl,proto3" json:"repository_url,omitempty"`
	DemoUrl          string                 `protobuf:"bytes,8,opt,name=demo_url,json=demoUrl,proto3" json:"demo_url,omitempty"`
	Thumbnail        string                 `protobuf:"bytes,9,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Featured         bool                   `protobuf:"varint,10,opt,name=featured,proto3" json:"featured,omitempty"`
	Status           string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	GithubStars      int32                  `protobuf:"varint,12,opt,name=github_stars,json=githubStars,proto3" json:"github_stars,omitempty"`
	GithubLastCommit *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=github_last_commit,json=githubLastCommit,proto3" json:"github_last_commit,omitempty"`
	ReadTime         int32                  `protobuf:"varint,14,opt,name=read_time,json=readTime,proto3" json:"read_time,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_project_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Project) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Project) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *Project) GetRepositoryUrl() string {
	if x != nil {
		return x.RepositoryUrl
	}
	return ""
}

func (x *Project) GetDemoUrl() string {
	if x != nil {
		return x.DemoUrl
	}
	return ""
}

func (x *Project) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *Project) GetFeatured() bool {
	if x != nil {
		return x.Featured
	}
	return false
}

func (x *Project) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Project) GetGithubStars() int32 {
	if x != nil {
		return x.GithubStars
	}
	return 0
}

func (x *Project) GetGithubLastCommit() *timestamppb.Timestamp {
	if x != nil {
		return x.GithubLastCommit
	}
	return nil
}

func (x *Project) GetReadTime() int32 {
	if x != nil {
		return x.ReadTime
	}
	return 0
}

func (x *Project) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Project) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_project_project_proto protoreflect.FileDescriptor

const file_project_project_proto_rawDesc = "" +
	"\n" +
	"\x15project/project.proto\x12\aproject\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x04\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\"\n" +
	"\farchitecture\x18\x06 \x01(\tR\farchitecture\x12%\n" +
	"\x0erepository_url\x18\a \x01(\tR\rrepositoryUrl\x12\x19\n" +
	"\bdemo_url\x18\b \x01(\tR\ademoUrl\x12\x1c\n" +
	"\tthumbnail\x18\t \x01(\tR\tthumbnail\x12\x1a\n" +
	"\bfeatured\x18\n" +
	" \x01(\bR\bfeatured\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12!\n" +
	"\fgithub_stars\x18\f \x01(\x05R\vgithubStars\x12H\n" +
	"\x12github_last_commit\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x10githubLastCommit\x12\x1b\n" +
	"\tread_time\x18\x0e \x01(\x05R\breadTime\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x1cZ\x1aportfolio-ai/proto/projectb\x06proto3"

var (
	file_project_project_proto_rawDescOnce sync.Once
	file_project_project_proto_rawDescData []byte
)

func file_project_project_proto_rawDescGZIP() []byte {
	file_project_project_proto_rawDescOnce.Do(func() {
		file_project_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_project_project_proto_rawDesc), len(file_project_project_proto_rawDesc)))
	})
	return file_project_project_proto_rawDescData
}

var file_project_project_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_project_project_proto_goTypes = []any{
	(*Project)(nil),               // 0: project.Project
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_project_project_proto_depIdxs = []int32{
	1, // 0: project.Project.github_last_commit:type_name -> google.protobuf.Timestamp
	1, // 1: project.Project.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: project.Project.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_project_project_proto_init() }
func file_project_project_proto_init() {
	if File_project_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_project_project_proto_rawDesc), len(file_project_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_project_project_proto_goTypes,
		DependencyIndexes: file_project_project_proto_depIdxs,
		MessageInfos:      file_project_project_proto_msgTypes,
	}.Build()
	File_project_project_proto = out.File
	file_project_project_proto_goTypes = nil
	file_project_project_proto_depIdxs = nil
}
