// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: skill/skill_service.proto

package skill

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListSkillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillsRequest) Reset() {
	*x = ListSkillsRequest{}
	mi := &file_skill_skill_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsRequest) ProtoMessage() {}

func (x *ListSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsRequest.ProtoReflect.Descriptor instead.
func (*ListSkillsRequest) Descriptor() ([]byte, []int) {
	return file_skill_skill_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListSkillsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSkillsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListSkillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []*Skill               `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillsResponse) Reset() {
	*x = ListSkillsResponse{}
	mi := &file_skill_skill_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsResponse) ProtoMessage() {}

func (x *ListSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsResponse.ProtoReflect.Descriptor instead.
func (*ListSkillsResponse) Descriptor() ([]byte, []int) {
	return file_skill_skill_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListSkillsResponse) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ListSkillsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillRequest) Reset() {
	*x = GetSkillRequest{}
	mi := &file_skill_skill_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillRequest) ProtoMessage() {}

func (x *GetSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillRequest.ProtoReflect.Descriptor instead.
func (*GetSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_skill_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetSkillRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skill         *Skill                 `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillResponse) Reset() {
	*x = GetSkillResponse{}
	mi := &file_skill_skill_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillResponse) ProtoMessage() {}

func (x *GetSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillResponse.ProtoReflect.Descriptor instead.
func (*GetSkillResponse) Descriptor() ([]byte, []int) {
	return file_skill_skill_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetSkillResponse) GetSkill() *Skill {
	if x != nil {
		return x.Skill
	}
	return nil
}

type CreateSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayOrder  int32                  `protobuf:"varint,1,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	TechnologyId  string                 `protobuf:"bytes,2,opt,name=technology_id,json=technologyId,proto3" json:"technology_id,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Years         float32                `protobuf:"fixed32,4,opt,name=years,proto3" json:"years,omitempty"`
	Favorite      bool                   `protobuf:"varint,5,opt,name=favorite,proto3" json:"favorite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkillRequest) Reset() {
	*x = CreateSkillRequest{}
	mi := &file_skill_skill_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillRequest) ProtoMessage() {}

func (x *CreateSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillRequest.ProtoReflect.Descriptor instead.
func (*CreateSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_skill_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSkillRequest) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *CreateSkillRequest) GetTechnologyId() string {
	if x != nil {
		return x.TechnologyId
	}
	return ""
}

func (x *CreateSkillRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *CreateSkillRequest) GetYears() float32 {
	if x != nil {
		return x.Years
	}
	return 0
}

func (x *CreateSkillRequest) GetFavorite() bool {
	if x != nil {
		return x.Favorite
	}
	return false
}

type CreateSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skill         *Skill                 `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkillResponse) Reset() {
	*x = CreateSkillResponse{}
	mi := &file_skill_skill_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillResponse) ProtoMessage() {}

func (x *CreateSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillResponse.ProtoReflect.Descriptor instead.
func (*CreateSkillResponse) Descriptor() ([]byte, []int) {
	return file_skill_skill_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSkillResponse) GetSkill() *Skill {
	if x != nil {
		return x.Skill
	}
	return nil
}

type UpdateSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayOrder  int32                  `protobuf:"varint,2,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	TechnologyId  string                 `protobuf:"bytes,3,opt,name=technology_id,json=technologyId,proto3" json:"technology_id,omitempty"`
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	Years         float32                `protobuf:"fixed32,5,opt,name=years,proto3" json:"years,omitempty"`
	Favorite      bool                   `protobuf:"varint,6,opt,name=favorite,proto3" json:"favorite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSkillRequest) Reset() {
	*x = UpdateSkillRequest{}
	mi := &file_skill_skill_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSkillRequest) ProtoMessage() {}

func (x *UpdateSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSkillRequest.ProtoReflect.Descriptor instead.
func (*UpdateSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_skill_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSkillRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSkillRequest) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *UpdateSkillRequest) GetTechnologyId() string {
	if x != nil {
		return x.TechnologyId
	}
	return ""
}

func (x *UpdateSkillRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *UpdateSkillRequest) GetYears() float32 {
	if x != nil {
		return x.Years
	}
	return 0
}

func (x *UpdateSkillRequest) GetFavorite() bool {
	if x != nil {
		return x.Favorite
	}
	return false
}

type UpdateSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skill         *Skill                 `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSkillResponse) Reset() {
	*x = UpdateSkillResponse{}
	mi := &file_skill_skill_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSkillResponse) ProtoMessage() {}

func (x *UpdateSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSkillResponse.ProtoReflect.Descriptor instead.
func (*UpdateSkillResponse) Descriptor() ([]byte, []int) {
	return file_skill_skill_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSkillResponse) GetSkill() *Skill {
	if x != nil {
		return x.Skill
	}
	return nil
}

type DeleteSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSkillRequest) Reset() {
	*x = DeleteSkillRequest{}
	mi := &file_skill_skill_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkillRequest) ProtoMessage() {}

func (x *DeleteSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkillRequest.ProtoReflect.Descriptor instead.
func (*DeleteSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_skill_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSkillRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSkillResponse) Reset() {
	*x = DeleteSkillResponse{}
	mi := &file_skill_skill_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkillResponse) ProtoMessage() {}

func (x *DeleteSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkillResponse.ProtoReflect.Descriptor instead.
func (*DeleteSkillResponse) Descriptor() ([]byte, []int) {
	return file_skill_skill_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteSkillResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_skill_skill_service_proto protoreflect.FileDescriptor

const file_skill_skill_service_proto_rawDesc = "" +
	"\n" +
	"\x19skill/skill_service.proto\x12\x05skill\x1a\x11skill/skill.proto\"=\n" +
	"\x11ListSkillsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"P\n" +
	"\x12ListSkillsResponse\x12$\n" +
	"\x06skills\x18\x01 \x03(\v2\f.skill.SkillR\x06skills\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"!\n" +
	"\x0fGetSkillRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x10GetSkillResponse\x12\"\n" +
	"\x05skill\x18\x01 \x01(\v2\f.skill.SkillR\x05skill\"\xa6\x01\n" +
	"\x12CreateSkillRequest\x12#\n" +
	"\rdisplay_order\x18\x01 \x01(\x05R\fdisplayOrder\x12#\n" +
	"\rtechnology_id\x18\x02 \x01(\tR\ftechnologyId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x14\n" +
	"\x05years\x18\x04 \x01(\x02R\x05years\x12\x1a\n" +
	"\bfavorite\x18\x05 \x01(\bR\bfavorite\"9\n" +
	"\x13CreateSkillResponse\x12\"\n" +
	"\x05skill\x18\x01 \x01(\v2\f.skill.SkillR\x05skill\"\xb6\x01\n" +
	"\x12UpdateSkillRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rdisplay_order\x18\x02 \x01(\x05R\fdisplayOrder\x12#\n" +
	"\rtechnology_id\x18\x03 \x01(\tR\ftechnologyId\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x14\n" +
	"\x05years\x18\x05 \x01(\x02R\x05years\x12\x1a\n" +
	"\bfavorite\x18\x06 \x01(\bR\bfavorite\"9\n" +
	"\x13UpdateSkillResponse\x12\"\n" +
	"\x05skill\x18\x01 \x01(\v2\f.skill.SkillR\x05skill\"$\n" +
	"\x12DeleteSkillRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13DeleteSkillResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe0\x02\n" +
	"\fSkillService\x12A\n" +
	"\n" +
	"ListSkills\x12\x18.skill.ListSkillsRequest\x1a\x19.skill.ListSkillsResponse\x12;\n" +
	"\bGetSkill\x12\x16.skill.GetSkillRequest\x1a\x17.skill.GetSkillResponse\x12D\n" +
	"\vCreateSkill\x12\x19.skill.CreateSkillRequest\x1a\x1a.skill.CreateSkillResponse\x12D\n" +
	"\vUpdateSkill\x12\x19.skill.UpdateSkillRequest\x1a\x1a.skill.UpdateSkillResponse\x12D\n" +
	"\vDeleteSkill\x12\x19.skill.DeleteSkillRequest\x1a\x1a.skill.DeleteSkillResponseB\x1aZ\x18portfolio-ai/proto/skillb\x06proto3"

var (
	file_skill_skill_service_proto_rawDescOnce sync.Once
	file_skill_skill_service_proto_rawDescData []byte
)

func file_skill_skill_service_proto_rawDescGZIP() []byte {
	file_skill_skill_service_proto_rawDescOnce.Do(func() {
		file_skill_skill_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skill_skill_service_proto_rawDesc), len(file_skill_skill_service_proto_rawDesc)))
	})
	return file_skill_skill_service_proto_rawDescData
}

var file_skill_skill_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_skill_skill_service_proto_goTypes = []any{
	(*ListSkillsRequest)(nil),   // 0: skill.ListSkillsRequest
	(*ListSkillsResponse)(nil),  // 1: skill.ListSkillsResponse
	(*GetSkillRequest)(nil),     // 2: skill.GetSkillRequest
	(*GetSkillResponse)(nil),    // 3: skill.GetSkillResponse
	(*CreateSkillRequest)(nil),  // 4: skill.CreateSkillRequest
	(*CreateSkillResponse)(nil), // 5: skill.CreateSkillResponse
	(*UpdateSkillRequest)(nil),  // 6: skill.UpdateSkillRequest
	(*UpdateSkillResponse)(nil), // 7: skill.UpdateSkillResponse
	(*DeleteSkillRequest)(nil),  // 8: skill.DeleteSkillRequest
	(*DeleteSkillResponse)(nil), // 9: skill.DeleteSkillResponse
	(*Skill)(nil),               // 10: skill.Skill
}
var file_skill_skill_service_proto_depIdxs = []int32{
	10, // 0: skill.ListSkillsResponse.skills:type_name -> skill.Skill
	10, // 1: skill.GetSkillResponse.skill:type_name -> skill.Skill
	10, // 2: skill.CreateSkillResponse.skill:type_name -> skill.Skill
	10, // 3: skill.UpdateSkillResponse.skill:type_name -> skill.Skill
	0,  // 4: skill.SkillService.ListSkills:input_type -> skill.ListSkillsRequest
	2,  // 5: skill.SkillService.GetSkill:input_type -> skill.GetSkillRequest
	4,  // 6: skill.SkillService.CreateSkill:input_type -> skill.CreateSkillRequest
	6,  // 7: skill.SkillService.UpdateSkill:input_type -> skill.UpdateSkillRequest
	8,  // 8: skill.SkillService.DeleteSkill:input_type -> skill.DeleteSkillRequest
	1,  // 9: skill.SkillService.ListSkills:output_type -> skill.ListSkillsResponse
	3,  // 10: skill.SkillService.GetSkill:output_type -> skill.GetSkillResponse
	5,  // 11: skill.SkillService.CreateSkill:output_type -> skill.CreateSkillResponse
	7,  // 12: skill.SkillService.UpdateSkill:output_type -> skill.UpdateSkillResponse
	9,  // 13: skill.SkillService.DeleteSkill:output_type -> skill.DeleteSkillResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_skill_skill_service_proto_init() }
func file_skill_skill_service_proto_init() {
	if File_skill_skill_service_proto != nil {
		return
	}
	file_skill_skill_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skill_skill_service_proto_rawDesc), len(file_skill_skill_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_skill_skill_service_proto_goTypes,
		DependencyIndexes: file_skill_skill_service_proto_depIdxs,
		MessageInfos:      file_skill_skill_service_proto_msgTypes,
	}.Build()
	File_skill_skill_service_proto = out.File
	file_skill_skill_service_proto_goTypes = nil
	file_skill_skill_service_proto_depIdxs = nil
}
