// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: skill/skill.proto

package skill

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	technology "portfolio-ai/proto/technology"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Skill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayOrder  int32                  `protobuf:"varint,2,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	TechnologyId  string                 `protobuf:"bytes,3,opt,name=technology_id,json=technologyId,proto3" json:"technology_id,omitempty"`
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	Years         float32                `protobuf:"fixed32,5,opt,name=years,proto3" json:"years,omitempty"`
	Favorite      bool                   `protobuf:"varint,6,opt,name=favorite,proto3" json:"favorite,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Technology    *technology.Technology `protobuf:"bytes,8,opt,name=technology,proto3" json:"technology,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_skill_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{0}
}

func (x *Skill) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Skill) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *Skill) GetTechnologyId() string {
	if x != nil {
		return x.TechnologyId
	}
	return ""
}

func (x *Skill) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Skill) GetYears() float32 {
	if x != nil {
		return x.Years
	}
	return 0
}

func (x *Skill) GetFavorite() bool {
	if x != nil {
		return x.Favorite
	}
	return false
}

func (x *Skill) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Skill) GetTechnology() *technology.Technology {
	if x != nil {
		return x.Technology
	}
	return nil
}

var File_skill_skill_proto protoreflect.FileDescriptor

const file_skill_skill_proto_rawDesc = "" +
	"\n" +
	"\x11skill/skill.proto\x12\x05skill\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1btechnology/technology.proto\"\x9c\x02\n" +
	"\x05Skill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rdisplay_order\x18\x02 \x01(\x05R\fdisplayOrder\x12#\n" +
	"\rtechnology_id\x18\x03 \x01(\tR\ftechnologyId\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x14\n" +
	"\x05years\x18\x05 \x01(\x02R\x05years\x12\x1a\n" +
	"\bfavorite\x18\x06 \x01(\bR\bfavorite\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x126\n" +
	"\n" +
	"technology\x18\b \x01(\v2\x16.technology.TechnologyR\n" +
	"technologyB\x1aZ\x18portfolio-ai/proto/skillb\x06proto3"

var (
	file_skill_skill_proto_rawDescOnce sync.Once
	file_skill_skill_proto_rawDescData []byte
)

func file_skill_skill_proto_rawDescGZIP() []byte {
	file_skill_skill_proto_rawDescOnce.Do(func() {
		file_skill_skill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skill_skill_proto_rawDesc), len(file_skill_skill_proto_rawDesc)))
	})
	return file_skill_skill_proto_rawDescData
}

var file_skill_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_skill_skill_proto_goTypes = []any{
	(*Skill)(nil),                 // 0: skill.Skill
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*technology.Technology)(nil), // 2: technology.Technology
}
var file_skill_skill_proto_depIdxs = []int32{
	1, // 0: skill.Skill.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: skill.Skill.technology:type_name -> technology.Technology
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_skill_skill_proto_init() }
func file_skill_skill_proto_init() {
	if File_skill_skill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skill_skill_proto_rawDesc), len(file_skill_skill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_skill_skill_proto_goTypes,
		DependencyIndexes: file_skill_skill_proto_depIdxs,
		MessageInfos:      file_skill_skill_proto_msgTypes,
	}.Build()
	File_skill_skill_proto = out.File
	file_skill_skill_proto_goTypes = nil
	file_skill_skill_proto_depIdxs = nil
}
