// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: certificate/certificate_service.proto

package certificate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCertificatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCertificatesRequest) Reset() {
	*x = ListCertificatesRequest{}
	mi := &file_certificate_certificate_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCertificatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCertificatesRequest) ProtoMessage() {}

func (x *ListCertificatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_certificate_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCertificatesRequest.ProtoReflect.Descriptor instead.
func (*ListCertificatesRequest) Descriptor() ([]byte, []int) {
	return file_certificate_certificate_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListCertificatesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCertificatesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListCertificatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificates  []*Certificate         `protobuf:"bytes,1,rep,name=certificates,proto3" json:"certificates,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCertificatesResponse) Reset() {
	*x = ListCertificatesResponse{}
	mi := &file_certificate_certificate_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCertificatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCertificatesResponse) ProtoMessage() {}

func (x *ListCertificatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_certificate_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCertificatesResponse.ProtoReflect.Descriptor instead.
func (*ListCertificatesResponse) Descriptor() ([]byte, []int) {
	return file_certificate_certificate_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListCertificatesResponse) GetCertificates() []*Certificate {
	if x != nil {
		return x.Certificates
	}
	return nil
}

func (x *ListCertificatesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertificateRequest) Reset() {
	*x = GetCertificateRequest{}
	mi := &file_certificate_certificate_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateRequest) ProtoMessage() {}

func (x *GetCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_certificate_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateRequest.ProtoReflect.Descriptor instead.
func (*GetCertificateRequest) Descriptor() ([]byte, []int) {
	return file_certificate_certificate_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetCertificateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   *Certificate           `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertificateResponse) Reset() {
	*x = GetCertificateResponse{}
	mi := &file_certificate_certificate_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateResponse) ProtoMessage() {}

func (x *GetCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_certificate_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateResponse.ProtoReflect.Descriptor instead.
func (*GetCertificateResponse) Descriptor() ([]byte, []int) {
	return file_certificate_certificate_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetCertificateResponse) GetCertificate() *Certificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type CreateCertificateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Title          string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Issuer         string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	IssueDate      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=issue_date,json=issueDate,proto3" json:"issue_date,omitempty"`
	ExpirationDate *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	CredentialId   string                 `protobuf:"bytes,5,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	CredentialUrl  string                 `protobuf:"bytes,6,opt,name=credential_url,json=credentialUrl,proto3" json:"credential_url,omitempty"`
	Thumbnail      string                 `protobuf:"bytes,7,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Skills         []string               `protobuf:"bytes,8,rep,name=skills,proto3" json:"skills,omitempty"`
	IssuerLogo     string                 `protobuf:"bytes,9,opt,name=issuer_logo,json=issuerLogo,proto3" json:"issuer_logo,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCertificateRequest) Reset() {
	*x = CreateCertificateRequest{}
	mi := &file_certificate_certificate_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCertificateRequest) ProtoMessage() {}

func (x *CreateCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_certificate_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCertificateRequest.ProtoReflect.Descriptor instead.
func (*CreateCertificateRequest) Descriptor() ([]byte, []int) {
	return file_certificate_certificate_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCertificateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCertificateRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *CreateCertificateRequest) GetIssueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.IssueDate
	}
	return nil
}

func (x *CreateCertificateRequest) GetExpirationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationDate
	}
	return nil
}

func (x *CreateCertificateRequest) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *CreateCertificateRequest) GetCredentialUrl() string {
	if x != nil {
		return x.CredentialUrl
	}
	return ""
}

func (x *CreateCertificateRequest) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *CreateCertificateRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *CreateCertificateRequest) GetIssuerLogo() string {
	if x != nil {
		return x.IssuerLogo
	}
	return ""
}

type CreateCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   *Certificate           `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCertificateResponse) Reset() {
	*x = CreateCertificateResponse{}
	mi := &file_certificate_certificate_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCertificateResponse) ProtoMessage() {}

func (x *CreateCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_certificate_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCertificateResponse.ProtoReflect.Descriptor instead.
func (*CreateCertificateResponse) Descriptor() ([]byte, []int) {
	return file_certificate_certificate_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCertificateResponse) GetCertificate() *Certificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type UpdateCertificateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Issuer         string                 `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	IssueDate      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=issue_date,json=issueDate,proto3" json:"issue_date,omitempty"`
	ExpirationDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	CredentialId   string                 `protobuf:"bytes,6,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	CredentialUrl  string                 `protobuf:"bytes,7,opt,name=credential_url,json=credentialUrl,proto3" json:"credential_url,omitempty"`
	Thumbnail      string                 `protobuf:"bytes,8,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Skills         []string               `protobuf:"bytes,9,rep,name=skills,proto3" json:"skills,omitempty"`
	IssuerLogo     string                 `protobuf:"bytes,10,opt,name=issuer_logo,json=issuerLogo,proto3" json:"issuer_logo,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateCertificateRequest) Reset() {
	*x = UpdateCertificateRequest{}
	mi := &file_certificate_certificate_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCertificateRequest) ProtoMessage() {}

func (x *UpdateCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_certificate_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCertificateRequest.ProtoReflect.Descriptor instead.
func (*UpdateCertificateRequest) Descriptor() ([]byte, []int) {
	return file_certificate_certificate_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCertificateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCertificateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateCertificateRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *UpdateCertificateRequest) GetIssueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.IssueDate
	}
	return nil
}

func (x *UpdateCertificateRequest) GetExpirationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationDate
	}
	return nil
}

func (x *UpdateCertificateRequest) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *UpdateCertificateRequest) GetCredentialUrl() string {
	if x != nil {
		return x.CredentialUrl
	}
	return ""
}

func (x *UpdateCertificateRequest) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *UpdateCertificateRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *UpdateCertificateRequest) GetIssuerLogo() string {
	if x != nil {
		return x.IssuerLogo
	}
	return ""
}

type UpdateCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   *Certificate           `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCertificateResponse) Reset() {
	*x = UpdateCertificateResponse{}
	mi := &file_certificate_certificate_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCertificateResponse) ProtoMessage() {}

func (x *UpdateCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_certificate_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCertificateResponse.ProtoReflect.Descriptor instead.
func (*UpdateCertificateResponse) Descriptor() ([]byte, []int) {
	return file_certificate_certificate_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCertificateResponse) GetCertificate() *Certificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type DeleteCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCertificateRequest) Reset() {
	*x = DeleteCertificateRequest{}
	mi := &file_certificate_certificate_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCertificateRequest) ProtoMessage() {}

func (x *DeleteCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_certificate_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCertificateRequest.ProtoReflect.Descriptor instead.
func (*DeleteCertificateRequest) Descriptor() ([]byte, []int) {
	return file_certificate_certificate_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCertificateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCertificateResponse) Reset() {
	*x = DeleteCertificateResponse{}
	mi := &file_certificate_certificate_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCertificateResponse) ProtoMessage() {}

func (x *DeleteCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_certificate_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCertificateResponse.ProtoReflect.Descriptor instead.
func (*DeleteCertificateResponse) Descriptor() ([]byte, []int) {
	return file_certificate_certificate_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCertificateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_certificate_certificate_service_proto protoreflect.FileDescriptor

const file_certificate_certificate_service_proto_rawDesc = "" +
	"\n" +
	"%certificate/certificate_service.proto\x12\vcertificate\x1a\x1dcertificate/certificate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\x17ListCertificatesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"n\n" +
	"\x18ListCertificatesResponse\x12<\n" +
	"\fcertificates\x18\x01 \x03(\v2\x18.certificate.CertificateR\fcertificates\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"'\n" +
	"\x15GetCertificateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\x16GetCertificateResponse\x12:\n" +
	"\vcertificate\x18\x01 \x01(\v2\x18.certificate.CertificateR\vcertificate\"\xeb\x02\n" +
	"\x18CreateCertificateRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x129\n" +
	"\n" +
	"issue_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tissueDate\x12C\n" +
	"\x0fexpiration_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0eexpirationDate\x12#\n" +
	"\rcredential_id\x18\x05 \x01(\tR\fcredentialId\x12%\n" +
	"\x0ecredential_url\x18\x06 \x01(\tR\rcredentialUrl\x12\x1c\n" +
	"\tthumbnail\x18\a \x01(\tR\tthumbnail\x12\x16\n" +
	"\x06skills\x18\b \x03(\tR\x06skills\x12\x1f\n" +
	"\vissuer_logo\x18\t \x01(\tR\n" +
	"issuerLogo\"W\n" +
	"\x19CreateCertificateResponse\x12:\n" +
	"\vcertificate\x18\x01 \x01(\v2\x18.certificate.CertificateR\vcertificate\"\xfb\x02\n" +
	"\x18UpdateCertificateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer\x129\n" +
	"\n" +
	"issue_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tissueDate\x12C\n" +
	"\x0fexpiration_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0eexpirationDate\x12#\n" +
	"\rcredential_id\x18\x06 \x01(\tR\fcredentialId\x12%\n" +
	"\x0ecredential_url\x18\a \x01(\tR\rcredentialUrl\x12\x1c\n" +
	"\tthumbnail\x18\b \x01(\tR\tthumbnail\x12\x16\n" +
	"\x06skills\x18\t \x03(\tR\x06skills\x12\x1f\n" +
	"\vissuer_logo\x18\n" +
	" \x01(\tR\n" +
	"issuerLogo\"W\n" +
	"\x19UpdateCertificateResponse\x12:\n" +
	"\vcertificate\x18\x01 \x01(\v2\x18.certificate.CertificateR\vcertificate\"*\n" +
	"\x18DeleteCertificateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x19DeleteCertificateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xfc\x03\n" +
	"\x12CertificateService\x12_\n" +
	"\x10ListCertificates\x12$.certificate.ListCertificatesRequest\x1a%.certificate.ListCertificatesResponse\x12Y\n" +
	"\x0eGetCertificate\x12\".certificate.GetCertificateRequest\x1a#.certificate.GetCertificateResponse\x12b\n" +
	"\x11CreateCertificate\x12%.certificate.CreateCertificateRequest\x1a&.certificate.CreateCertificateResponse\x12b\n" +
	"\x11UpdateCertificate\x12%.certificate.UpdateCertificateRequest\x1a&.certificate.UpdateCertificateResponse\x12b\n" +
	"\x11DeleteCertificate\x12%.certificate.DeleteCertificateRequest\x1a&.certificate.DeleteCertificateResponseB Z\x1eportfolio-ai/proto/certificateb\x06proto3"

var (
	file_certificate_certificate_service_proto_rawDescOnce sync.Once
	file_certificate_certificate_service_proto_rawDescData []byte
)

func file_certificate_certificate_service_proto_rawDescGZIP() []byte {
	file_certificate_certificate_service_proto_rawDescOnce.Do(func() {
		file_certificate_certificate_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_certificate_certificate_service_proto_rawDesc), len(file_certificate_certificate_service_proto_rawDesc)))
	})
	return file_certificate_certificate_service_proto_rawDescData
}

var file_certificate_certificate_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_certificate_certificate_service_proto_goTypes = []any{
	(*ListCertificatesRequest)(nil),   // 0: certificate.ListCertificatesRequest
	(*ListCertificatesResponse)(nil),  // 1: certificate.ListCertificatesResponse
	(*GetCertificateRequest)(nil),     // 2: certificate.GetCertificateRequest
	(*GetCertificateResponse)(nil),    // 3: certificate.GetCertificateResponse
	(*CreateCertificateRequest)(nil),  // 4: certificate.CreateCertificateRequest
	(*CreateCertificateResponse)(nil), // 5: certificate.CreateCertificateResponse
	(*UpdateCertificateRequest)(nil),  // 6: certificate.UpdateCertificateRequest
	(*UpdateCertificateResponse)(nil), // 7: certificate.UpdateCertificateResponse
	(*DeleteCertificateRequest)(nil),  // 8: certificate.DeleteCertificateRequest
	(*DeleteCertificateResponse)(nil), // 9: certificate.DeleteCertificateResponse
	(*Certificate)(nil),               // 10: certificate.Certificate
	(*timestamppb.Timestamp)(nil),     // 11: google.protobuf.Timestamp
}
var file_certificate_certificate_service_proto_depIdxs = []int32{
	10, // 0: certificate.ListCertificatesResponse.certificates:type_name -> certificate.Certificate
	10, // 1: certificate.GetCertificateResponse.certificate:type_name -> certificate.Certificate
	11, // 2: certificate.CreateCertificateRequest.issue_date:type_name -> google.protobuf.Timestamp
	11, // 3: certificate.CreateCertificateRequest.expiration_date:type_name -> google.protobuf.Timestamp
	10, // 4: certificate.CreateCertificateResponse.certificate:type_name -> certificate.Certificate
	11, // 5: certificate.UpdateCertificateRequest.issue_date:type_name -> google.protobuf.Timestamp
	11, // 6: certificate.UpdateCertificateRequest.expiration_date:type_name -> google.protobuf.Timestamp
	10, // 7: certificate.UpdateCertificateResponse.certificate:type_name -> certificate.Certificate
	0,  // 8: certificate.CertificateService.ListCertificates:input_type -> certificate.ListCertificatesRequest
	2,  // 9: certificate.CertificateService.GetCertificate:input_type -> certificate.GetCertificateRequest
	4,  // 10: certificate.CertificateService.CreateCertificate:input_type -> certificate.CreateCertificateRequest
	6,  // 11: certificate.CertificateService.UpdateCertificate:input_type -> certificate.UpdateCertificateRequest
	8,  // 12: certificate.CertificateService.DeleteCertificate:input_type -> certificate.DeleteCertificateRequest
	1,  // 13: certificate.CertificateService.ListCertificates:output_type -> certificate.ListCertificatesResponse
	3,  // 14: certificate.CertificateService.GetCertificate:output_type -> certificate.GetCertificateResponse
	5,  // 15: certificate.CertificateService.CreateCertificate:output_type -> certificate.CreateCertificateResponse
	7,  // 16: certificate.CertificateService.UpdateCertificate:output_type -> certificate.UpdateCertificateResponse
	9,  // 17: certificate.CertificateService.DeleteCertificate:output_type -> certificate.DeleteCertificateResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_certificate_certificate_service_proto_init() }
func file_certificate_certificate_service_proto_init() {
	if File_certificate_certificate_service_proto != nil {
		return
	}
	file_certificate_certificate_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_certificate_certificate_service_proto_rawDesc), len(file_certificate_certificate_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_certificate_certificate_service_proto_goTypes,
		DependencyIndexes: file_certificate_certificate_service_proto_depIdxs,
		MessageInfos:      file_certificate_certificate_service_proto_msgTypes,
	}.Build()
	File_certificate_certificate_service_proto = out.File
	file_certificate_certificate_service_proto_goTypes = nil
	file_certificate_certificate_service_proto_depIdxs = nil
}
