// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: certificate/certificate.proto

package certificate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Certificate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Issuer         string                 `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	IssueDate      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=issue_date,json=issueDate,proto3" json:"issue_date,omitempty"`
	ExpirationDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	CredentialId   string                 `protobuf:"bytes,6,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	CredentialUrl  string                 `protobuf:"bytes,7,opt,name=credential_url,json=credentialUrl,proto3" json:"credential_url,omitempty"`
	Thumbnail      string                 `protobuf:"bytes,8,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Skills         []string               `protobuf:"bytes,9,rep,name=skills,proto3" json:"skills,omitempty"`
	IssuerLogo     string                 `protobuf:"bytes,10,opt,name=issuer_logo,json=issuerLogo,proto3" json:"issuer_logo,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_certificate_certificate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_certificate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_certificate_certificate_proto_rawDescGZIP(), []int{0}
}

func (x *Certificate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Certificate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Certificate) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Certificate) GetIssueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.IssueDate
	}
	return nil
}

func (x *Certificate) GetExpirationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationDate
	}
	return nil
}

func (x *Certificate) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *Certificate) GetCredentialUrl() string {
	if x != nil {
		return x.CredentialUrl
	}
	return ""
}

func (x *Certificate) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *Certificate) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *Certificate) GetIssuerLogo() string {
	if x != nil {
		return x.IssuerLogo
	}
	return ""
}

func (x *Certificate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_certificate_certificate_proto protoreflect.FileDescriptor

const file_certificate_certificate_proto_rawDesc = "" +
	"\n" +
	"\x1dcertificate/certificate.proto\x12\vcertificate\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x03\n" +
	"\vCertificate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer\x129\n" +
	"\n" +
	"issue_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tissueDate\x12C\n" +
	"\x0fexpiration_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0eexpirationDate\x12#\n" +
	"\rcredential_id\x18\x06 \x01(\tR\fcredentialId\x12%\n" +
	"\x0ecredential_url\x18\a \x01(\tR\rcredentialUrl\x12\x1c\n" +
	"\tthumbnail\x18\b \x01(\tR\tthumbnail\x12\x16\n" +
	"\x06skills\x18\t \x03(\tR\x06skills\x12\x1f\n" +
	"\vissuer_logo\x18\n" +
	" \x01(\tR\n" +
	"issuerLogo\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB Z\x1eportfolio-ai/proto/certificateb\x06proto3"

var (
	file_certificate_certificate_proto_rawDescOnce sync.Once
	file_certificate_certificate_proto_rawDescData []byte
)

func file_certificate_certificate_proto_rawDescGZIP() []byte {
	file_certificate_certificate_proto_rawDescOnce.Do(func() {
		file_certificate_certificate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_certificate_certificate_proto_rawDesc), len(file_certificate_certificate_proto_rawDesc)))
	})
	return file_certificate_certificate_proto_rawDescData
}

var file_certificate_certificate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_certificate_certificate_proto_goTypes = []any{
	(*Certificate)(nil),           // 0: certificate.Certificate
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_certificate_certificate_proto_depIdxs = []int32{
	1, // 0: certificate.Certificate.issue_date:type_name -> google.protobuf.Timestamp
	1, // 1: certificate.Certificate.expiration_date:type_name -> google.protobuf.Timestamp
	1, // 2: certificate.Certificate.created_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_certificate_certificate_proto_init() }
func file_certificate_certificate_proto_init() {
	if File_certificate_certificate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_certificate_certificate_proto_rawDesc), len(file_certificate_certificate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_certificate_certificate_proto_goTypes,
		DependencyIndexes: file_certificate_certificate_proto_depIdxs,
		MessageInfos:      file_certificate_certificate_proto_msgTypes,
	}.Build()
	File_certificate_certificate_proto = out.File
	file_certificate_certificate_proto_goTypes = nil
	file_certificate_certificate_proto_depIdxs = nil
}
