// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: experience/experience.proto

package experience

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Experience struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Company        string                 `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	Position       string                 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	EmploymentType string                 `protobuf:"bytes,4,opt,name=employment_type,json=employmentType,proto3" json:"employment_type,omitempty"`
	StartDate      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	CurrentJob     bool                   `protobuf:"varint,7,opt,name=current_job,json=currentJob,proto3" json:"current_job,omitempty"`
	Location       string                 `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	Description    string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	DisplayOrder   int32                  `protobuf:"varint,10,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	CompanyLogo    string                 `protobuf:"bytes,11,opt,name=company_logo,json=companyLogo,proto3" json:"company_logo,omitempty"`
	Skills         []string               `protobuf:"bytes,12,rep,name=skills,proto3" json:"skills,omitempty"`
	RemoteType     string                 `protobuf:"bytes,13,opt,name=remote_type,json=remoteType,proto3" json:"remote_type,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Experience) Reset() {
	*x = Experience{}
	mi := &file_experience_experience_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Experience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Experience) ProtoMessage() {}

func (x *Experience) ProtoReflect() protoreflect.Message {
	mi := &file_experience_experience_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Experience.ProtoReflect.Descriptor instead.
func (*Experience) Descriptor() ([]byte, []int) {
	return file_experience_experience_proto_rawDescGZIP(), []int{0}
}

func (x *Experience) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Experience) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Experience) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Experience) GetEmploymentType() string {
	if x != nil {
		return x.EmploymentType
	}
	return ""
}

func (x *Experience) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Experience) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *Experience) GetCurrentJob() bool {
	if x != nil {
		return x.CurrentJob
	}
	return false
}

func (x *Experience) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Experience) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Experience) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *Experience) GetCompanyLogo() string {
	if x != nil {
		return x.CompanyLogo
	}
	return ""
}

func (x *Experience) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *Experience) GetRemoteType() string {
	if x != nil {
		return x.RemoteType
	}
	return ""
}

func (x *Experience) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Experience) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_experience_experience_proto protoreflect.FileDescriptor

const file_experience_experience_proto_rawDesc = "" +
	"\n" +
	"\x1bexperience/experience.proto\x12\n" +
	"experience\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc3\x04\n" +
	"\n" +
	"Experience\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acompany\x18\x02 \x01(\tR\acompany\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\tR\bposition\x12'\n" +
	"\x0femployment_type\x18\x04 \x01(\tR\x0eemploymentType\x129\n" +
	"\n" +
	"start_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x1f\n" +
	"\vcurrent_job\x18\a \x01(\bR\n" +
	"currentJob\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12#\n" +
	"\rdisplay_order\x18\n" +
	" \x01(\x05R\fdisplayOrder\x12!\n" +
	"\fcompany_logo\x18\v \x01(\tR\vcompanyLogo\x12\x16\n" +
	"\x06skills\x18\f \x03(\tR\x06skills\x12\x1f\n" +
	"\vremote_type\x18\r \x01(\tR\n" +
	"remoteType\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x1fZ\x1dportfolio-ai/proto/experienceb\x06proto3"

var (
	file_experience_experience_proto_rawDescOnce sync.Once
	file_experience_experience_proto_rawDescData []byte
)

func file_experience_experience_proto_rawDescGZIP() []byte {
	file_experience_experience_proto_rawDescOnce.Do(func() {
		file_experience_experience_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_experience_experience_proto_rawDesc), len(file_experience_experience_proto_rawDesc)))
	})
	return file_experience_experience_proto_rawDescData
}

var file_experience_experience_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_experience_experience_proto_goTypes = []any{
	(*Experience)(nil),            // 0: experience.Experience
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_experience_experience_proto_depIdxs = []int32{
	1, // 0: experience.Experience.start_date:type_name -> google.protobuf.Timestamp
	1, // 1: experience.Experience.end_date:type_name -> google.protobuf.Timestamp
	1, // 2: experience.Experience.created_at:type_name -> google.protobuf.Timestamp
	1, // 3: experience.Experience.updated_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_experience_experience_proto_init() }
func file_experience_experience_proto_init() {
	if File_experience_experience_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_experience_experience_proto_rawDesc), len(file_experience_experience_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_experience_experience_proto_goTypes,
		DependencyIndexes: file_experience_experience_proto_depIdxs,
		MessageInfos:      file_experience_experience_proto_msgTypes,
	}.Build()
	File_experience_experience_proto = out.File
	file_experience_experience_proto_goTypes = nil
	file_experience_experience_proto_depIdxs = nil
}
