// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: experience/experience_service.proto

package experience

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListExperiencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExperiencesRequest) Reset() {
	*x = ListExperiencesRequest{}
	mi := &file_experience_experience_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExperiencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExperiencesRequest) ProtoMessage() {}

func (x *ListExperiencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_experience_experience_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExperiencesRequest.ProtoReflect.Descriptor instead.
func (*ListExperiencesRequest) Descriptor() ([]byte, []int) {
	return file_experience_experience_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListExperiencesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListExperiencesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListExperiencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Experiences   []*Experience          `protobuf:"bytes,1,rep,name=experiences,proto3" json:"experiences,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExperiencesResponse) Reset() {
	*x = ListExperiencesResponse{}
	mi := &file_experience_experience_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExperiencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExperiencesResponse) ProtoMessage() {}

func (x *ListExperiencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_experience_experience_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExperiencesResponse.ProtoReflect.Descriptor instead.
func (*ListExperiencesResponse) Descriptor() ([]byte, []int) {
	return file_experience_experience_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListExperiencesResponse) GetExperiences() []*Experience {
	if x != nil {
		return x.Experiences
	}
	return nil
}

func (x *ListExperiencesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetExperienceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExperienceRequest) Reset() {
	*x = GetExperienceRequest{}
	mi := &file_experience_experience_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExperienceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExperienceRequest) ProtoMessage() {}

func (x *GetExperienceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_experience_experience_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExperienceRequest.ProtoReflect.Descriptor instead.
func (*GetExperienceRequest) Descriptor() ([]byte, []int) {
	return file_experience_experience_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetExperienceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetExperienceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Experience    *Experience            `protobuf:"bytes,1,opt,name=experience,proto3" json:"experience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExperienceResponse) Reset() {
	*x = GetExperienceResponse{}
	mi := &file_experience_experience_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExperienceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExperienceResponse) ProtoMessage() {}

func (x *GetExperienceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_experience_experience_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExperienceResponse.ProtoReflect.Descriptor instead.
func (*GetExperienceResponse) Descriptor() ([]byte, []int) {
	return file_experience_experience_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetExperienceResponse) GetExperience() *Experience {
	if x != nil {
		return x.Experience
	}
	return nil
}

type CreateExperienceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Company        string                 `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	Position       string                 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	EmploymentType string                 `protobuf:"bytes,3,opt,name=employment_type,json=employmentType,proto3" json:"employment_type,omitempty"`
	StartDate      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	CurrentJob     bool                   `protobuf:"varint,6,opt,name=current_job,json=currentJob,proto3" json:"current_job,omitempty"`
	Location       string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Description    string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	DisplayOrder   int32                  `protobuf:"varint,9,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	CompanyLogo    string                 `protobuf:"bytes,10,opt,name=company_logo,json=companyLogo,proto3" json:"company_logo,omitempty"`
	Skills         []string               `protobuf:"bytes,11,rep,name=skills,proto3" json:"skills,omitempty"`
	RemoteType     string                 `protobuf:"bytes,12,opt,name=remote_type,json=remoteType,proto3" json:"remote_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateExperienceRequest) Reset() {
	*x = CreateExperienceRequest{}
	mi := &file_experience_experience_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExperienceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExperienceRequest) ProtoMessage() {}

func (x *CreateExperienceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_experience_experience_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExperienceRequest.ProtoReflect.Descriptor instead.
func (*CreateExperienceRequest) Descriptor() ([]byte, []int) {
	return file_experience_experience_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateExperienceRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *CreateExperienceRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *CreateExperienceRequest) GetEmploymentType() string {
	if x != nil {
		return x.EmploymentType
	}
	return ""
}

func (x *CreateExperienceRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *CreateExperienceRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *CreateExperienceRequest) GetCurrentJob() bool {
	if x != nil {
		return x.CurrentJob
	}
	return false
}

func (x *CreateExperienceRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateExperienceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateExperienceRequest) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *CreateExperienceRequest) GetCompanyLogo() string {
	if x != nil {
		return x.CompanyLogo
	}
	return ""
}

func (x *CreateExperienceRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *CreateExperienceRequest) GetRemoteType() string {
	if x != nil {
		return x.RemoteType
	}
	return ""
}

type CreateExperienceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Experience    *Experience            `protobuf:"bytes,1,opt,name=experience,proto3" json:"experience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExperienceResponse) Reset() {
	*x = CreateExperienceResponse{}
	mi := &file_experience_experience_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExperienceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExperienceResponse) ProtoMessage() {}

func (x *CreateExperienceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_experience_experience_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExperienceResponse.ProtoReflect.Descriptor instead.
func (*CreateExperienceResponse) Descriptor() ([]byte, []int) {
	return file_experience_experience_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateExperienceResponse) GetExperience() *Experience {
	if x != nil {
		return x.Experience
	}
	return nil
}

type UpdateExperienceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Company        string                 `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	Position       string                 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	EmploymentType string                 `protobuf:"bytes,4,opt,name=employment_type,json=employmentType,proto3" json:"employment_type,omitempty"`
	StartDate      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	CurrentJob     bool                   `protobuf:"varint,7,opt,name=current_job,json=currentJob,proto3" json:"current_job,omitempty"`
	Location       string                 `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	Description    string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	DisplayOrder   int32                  `protobuf:"varint,10,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	CompanyLogo    string                 `protobuf:"bytes,11,opt,name=company_logo,json=companyLogo,proto3" json:"company_logo,omitempty"`
	Skills         []string               `protobuf:"bytes,12,rep,name=skills,proto3" json:"skills,omitempty"`
	RemoteType     string                 `protobuf:"bytes,13,opt,name=remote_type,json=remoteType,proto3" json:"remote_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateExperienceRequest) Reset() {
	*x = UpdateExperienceRequest{}
	mi := &file_experience_experience_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExperienceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExperienceRequest) ProtoMessage() {}

func (x *UpdateExperienceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_experience_experience_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExperienceRequest.ProtoReflect.Descriptor instead.
func (*UpdateExperienceRequest) Descriptor() ([]byte, []int) {
	return file_experience_experience_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateExperienceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateExperienceRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *UpdateExperienceRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *UpdateExperienceRequest) GetEmploymentType() string {
	if x != nil {
		return x.EmploymentType
	}
	return ""
}

func (x *UpdateExperienceRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *UpdateExperienceRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *UpdateExperienceRequest) GetCurrentJob() bool {
	if x != nil {
		return x.CurrentJob
	}
	return false
}

func (x *UpdateExperienceRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateExperienceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateExperienceRequest) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *UpdateExperienceRequest) GetCompanyLogo() string {
	if x != nil {
		return x.CompanyLogo
	}
	return ""
}

func (x *UpdateExperienceRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *UpdateExperienceRequest) GetRemoteType() string {
	if x != nil {
		return x.RemoteType
	}
	return ""
}

type UpdateExperienceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Experience    *Experience            `protobuf:"bytes,1,opt,name=experience,proto3" json:"experience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExperienceResponse) Reset() {
	*x = UpdateExperienceResponse{}
	mi := &file_experience_experience_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExperienceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExperienceResponse) ProtoMessage() {}

func (x *UpdateExperienceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_experience_experience_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExperienceResponse.ProtoReflect.Descriptor instead.
func (*UpdateExperienceResponse) Descriptor() ([]byte, []int) {
	return file_experience_experience_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateExperienceResponse) GetExperience() *Experience {
	if x != nil {
		return x.Experience
	}
	return nil
}

type DeleteExperienceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExperienceRequest) Reset() {
	*x = DeleteExperienceRequest{}
	mi := &file_experience_experience_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExperienceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExperienceRequest) ProtoMessage() {}

func (x *DeleteExperienceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_experience_experience_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExperienceRequest.ProtoReflect.Descriptor instead.
func (*DeleteExperienceRequest) Descriptor() ([]byte, []int) {
	return file_experience_experience_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteExperienceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteExperienceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExperienceResponse) Reset() {
	*x = DeleteExperienceResponse{}
	mi := &file_experience_experience_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExperienceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExperienceResponse) ProtoMessage() {}

func (x *DeleteExperienceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_experience_experience_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExperienceResponse.ProtoReflect.Descriptor instead.
func (*DeleteExperienceResponse) Descriptor() ([]byte, []int) {
	return file_experience_experience_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteExperienceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_experience_experience_service_proto protoreflect.FileDescriptor

const file_experience_experience_service_proto_rawDesc = "" +
	"\n" +
	"#experience/experience_service.proto\x12\n" +
	"experience\x1a\x1bexperience/experience.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"B\n" +
	"\x16ListExperiencesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"i\n" +
	"\x17ListExperiencesResponse\x128\n" +
	"\vexperiences\x18\x01 \x03(\v2\x16.experience.ExperienceR\vexperiences\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"&\n" +
	"\x14GetExperienceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x15GetExperienceResponse\x126\n" +
	"\n" +
	"experience\x18\x01 \x01(\v2\x16.experience.ExperienceR\n" +
	"experience\"\xca\x03\n" +
	"\x17CreateExperienceRequest\x12\x18\n" +
	"\acompany\x18\x01 \x01(\tR\acompany\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\tR\bposition\x12'\n" +
	"\x0femployment_type\x18\x03 \x01(\tR\x0eemploymentType\x129\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x1f\n" +
	"\vcurrent_job\x18\x06 \x01(\bR\n" +
	"currentJob\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12#\n" +
	"\rdisplay_order\x18\t \x01(\x05R\fdisplayOrder\x12!\n" +
	"\fcompany_logo\x18\n" +
	" \x01(\tR\vcompanyLogo\x12\x16\n" +
	"\x06skills\x18\v \x03(\tR\x06skills\x12\x1f\n" +
	"\vremote_type\x18\f \x01(\tR\n" +
	"remoteType\"R\n" +
	"\x18CreateExperienceResponse\x126\n" +
	"\n" +
	"experience\x18\x01 \x01(\v2\x16.experience.ExperienceR\n" +
	"experience\"\xda\x03\n" +
	"\x17UpdateExperienceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acompany\x18\x02 \x01(\tR\acompany\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\tR\bposition\x12'\n" +
	"\x0femployment_type\x18\x04 \x01(\tR\x0eemploymentType\x129\n" +
	"\n" +
	"start_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x1f\n" +
	"\vcurrent_job\x18\a \x01(\bR\n" +
	"currentJob\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12#\n" +
	"\rdisplay_order\x18\n" +
	" \x01(\x05R\fdisplayOrder\x12!\n" +
	"\fcompany_logo\x18\v \x01(\tR\vcompanyLogo\x12\x16\n" +
	"\x06skills\x18\f \x03(\tR\x06skills\x12\x1f\n" +
	"\vremote_type\x18\r \x01(\tR\n" +
	"remoteType\"R\n" +
	"\x18UpdateExperienceResponse\x126\n" +
	"\n" +
	"experience\x18\x01 \x01(\v2\x16.experience.ExperienceR\n" +
	"experience\")\n" +
	"\x17DeleteExperienceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x18DeleteExperienceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe2\x03\n" +
	"\x11ExperienceService\x12Z\n" +
	"\x0fListExperiences\x12\".experience.ListExperiencesRequest\x1a#.experience.ListExperiencesResponse\x12T\n" +
	"\rGetExperience\x12 .experience.GetExperienceRequest\x1a!.experience.GetExperienceResponse\x12]\n" +
	"\x10CreateExperience\x12#.experience.CreateExperienceRequest\x1a$.experience.CreateExperienceResponse\x12]\n" +
	"\x10UpdateExperience\x12#.experience.UpdateExperienceRequest\x1a$.experience.UpdateExperienceResponse\x12]\n" +
	"\x10DeleteExperience\x12#.experience.DeleteExperienceRequest\x1a$.experience.DeleteExperienceResponseB\x1fZ\x1dportfolio-ai/proto/experienceb\x06proto3"

var (
	file_experience_experience_service_proto_rawDescOnce sync.Once
	file_experience_experience_service_proto_rawDescData []byte
)

func file_experience_experience_service_proto_rawDescGZIP() []byte {
	file_experience_experience_service_proto_rawDescOnce.Do(func() {
		file_experience_experience_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_experience_experience_service_proto_rawDesc), len(file_experience_experience_service_proto_rawDesc)))
	})
	return file_experience_experience_service_proto_rawDescData
}

var file_experience_experience_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_experience_experience_service_proto_goTypes = []any{
	(*ListExperiencesRequest)(nil),   // 0: experience.ListExperiencesRequest
	(*ListExperiencesResponse)(nil),  // 1: experience.ListExperiencesResponse
	(*GetExperienceRequest)(nil),     // 2: experience.GetExperienceRequest
	(*GetExperienceResponse)(nil),    // 3: experience.GetExperienceResponse
	(*CreateExperienceRequest)(nil),  // 4: experience.CreateExperienceRequest
	(*CreateExperienceResponse)(nil), // 5: experience.CreateExperienceResponse
	(*UpdateExperienceRequest)(nil),  // 6: experience.UpdateExperienceRequest
	(*UpdateExperienceResponse)(nil), // 7: experience.UpdateExperienceResponse
	(*DeleteExperienceRequest)(nil),  // 8: experience.DeleteExperienceRequest
	(*DeleteExperienceResponse)(nil), // 9: experience.DeleteExperienceResponse
	(*Experience)(nil),               // 10: experience.Experience
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
}
var file_experience_experience_service_proto_depIdxs = []int32{
	10, // 0: experience.ListExperiencesResponse.experiences:type_name -> experience.Experience
	10, // 1: experience.GetExperienceResponse.experience:type_name -> experience.Experience
	11, // 2: experience.CreateExperienceRequest.start_date:type_name -> google.protobuf.Timestamp
	11, // 3: experience.CreateExperienceRequest.end_date:type_name -> google.protobuf.Timestamp
	10, // 4: experience.CreateExperienceResponse.experience:type_name -> experience.Experience
	11, // 5: experience.UpdateExperienceRequest.start_date:type_name -> google.protobuf.Timestamp
	11, // 6: experience.UpdateExperienceRequest.end_date:type_name -> google.protobuf.Timestamp
	10, // 7: experience.UpdateExperienceResponse.experience:type_name -> experience.Experience
	0,  // 8: experience.ExperienceService.ListExperiences:input_type -> experience.ListExperiencesRequest
	2,  // 9: experience.ExperienceService.GetExperience:input_type -> experience.GetExperienceRequest
	4,  // 10: experience.ExperienceService.CreateExperience:input_type -> experience.CreateExperienceRequest
	6,  // 11: experience.ExperienceService.UpdateExperience:input_type -> experience.UpdateExperienceRequest
	8,  // 12: experience.ExperienceService.DeleteExperience:input_type -> experience.DeleteExperienceRequest
	1,  // 13: experience.ExperienceService.ListExperiences:output_type -> experience.ListExperiencesResponse
	3,  // 14: experience.ExperienceService.GetExperience:output_type -> experience.GetExperienceResponse
	5,  // 15: experience.ExperienceService.CreateExperience:output_type -> experience.CreateExperienceResponse
	7,  // 16: experience.ExperienceService.UpdateExperience:output_type -> experience.UpdateExperienceResponse
	9,  // 17: experience.ExperienceService.DeleteExperience:output_type -> experience.DeleteExperienceResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_experience_experience_service_proto_init() }
func file_experience_experience_service_proto_init() {
	if File_experience_experience_service_proto != nil {
		return
	}
	file_experience_experience_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_experience_experience_service_proto_rawDesc), len(file_experience_experience_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_experience_experience_service_proto_goTypes,
		DependencyIndexes: file_experience_experience_service_proto_depIdxs,
		MessageInfos:      file_experience_experience_service_proto_msgTypes,
	}.Build()
	File_experience_experience_service_proto = out.File
	file_experience_experience_service_proto_goTypes = nil
	file_experience_experience_service_proto_depIdxs = nil
}
