// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: technology/technology_service.proto

package technology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTechnologiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTechnologiesRequest) Reset() {
	*x = ListTechnologiesRequest{}
	mi := &file_technology_technology_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTechnologiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTechnologiesRequest) ProtoMessage() {}

func (x *ListTechnologiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_technology_technology_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTechnologiesRequest.ProtoReflect.Descriptor instead.
func (*ListTechnologiesRequest) Descriptor() ([]byte, []int) {
	return file_technology_technology_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListTechnologiesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTechnologiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListTechnologiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Technologies  []*Technology          `protobuf:"bytes,1,rep,name=technologies,proto3" json:"technologies,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTechnologiesResponse) Reset() {
	*x = ListTechnologiesResponse{}
	mi := &file_technology_technology_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTechnologiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTechnologiesResponse) ProtoMessage() {}

func (x *ListTechnologiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_technology_technology_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTechnologiesResponse.ProtoReflect.Descriptor instead.
func (*ListTechnologiesResponse) Descriptor() ([]byte, []int) {
	return file_technology_technology_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListTechnologiesResponse) GetTechnologies() []*Technology {
	if x != nil {
		return x.Technologies
	}
	return nil
}

func (x *ListTechnologiesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetTechnologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTechnologyRequest) Reset() {
	*x = GetTechnologyRequest{}
	mi := &file_technology_technology_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTechnologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTechnologyRequest) ProtoMessage() {}

func (x *GetTechnologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_technology_technology_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTechnologyRequest.ProtoReflect.Descriptor instead.
func (*GetTechnologyRequest) Descriptor() ([]byte, []int) {
	return file_technology_technology_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTechnologyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTechnologyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Technology    *Technology            `protobuf:"bytes,1,opt,name=technology,proto3" json:"technology,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTechnologyResponse) Reset() {
	*x = GetTechnologyResponse{}
	mi := &file_technology_technology_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTechnologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTechnologyResponse) ProtoMessage() {}

func (x *GetTechnologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_technology_technology_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTechnologyResponse.ProtoReflect.Descriptor instead.
func (*GetTechnologyResponse) Descriptor() ([]byte, []int) {
	return file_technology_technology_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTechnologyResponse) GetTechnology() *Technology {
	if x != nil {
		return x.Technology
	}
	return nil
}

type CreateTechnologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	OfficialUrl   string                 `protobuf:"bytes,5,opt,name=official_url,json=officialUrl,proto3" json:"official_url,omitempty"`
	Logo          string                 `protobuf:"bytes,6,opt,name=logo,proto3" json:"logo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTechnologyRequest) Reset() {
	*x = CreateTechnologyRequest{}
	mi := &file_technology_technology_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTechnologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTechnologyRequest) ProtoMessage() {}

func (x *CreateTechnologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_technology_technology_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTechnologyRequest.ProtoReflect.Descriptor instead.
func (*CreateTechnologyRequest) Descriptor() ([]byte, []int) {
	return file_technology_technology_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTechnologyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTechnologyRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateTechnologyRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CreateTechnologyRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CreateTechnologyRequest) GetOfficialUrl() string {
	if x != nil {
		return x.OfficialUrl
	}
	return ""
}

func (x *CreateTechnologyRequest) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

type CreateTechnologyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Technology    *Technology            `protobuf:"bytes,1,opt,name=technology,proto3" json:"technology,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTechnologyResponse) Reset() {
	*x = CreateTechnologyResponse{}
	mi := &file_technology_technology_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTechnologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTechnologyResponse) ProtoMessage() {}

func (x *CreateTechnologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_technology_technology_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTechnologyResponse.ProtoReflect.Descriptor instead.
func (*CreateTechnologyResponse) Descriptor() ([]byte, []int) {
	return file_technology_technology_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTechnologyResponse) GetTechnology() *Technology {
	if x != nil {
		return x.Technology
	}
	return nil
}

type UpdateTechnologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	OfficialUrl   string                 `protobuf:"bytes,6,opt,name=official_url,json=officialUrl,proto3" json:"official_url,omitempty"`
	Logo          string                 `protobuf:"bytes,7,opt,name=logo,proto3" json:"logo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTechnologyRequest) Reset() {
	*x = UpdateTechnologyRequest{}
	mi := &file_technology_technology_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTechnologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTechnologyRequest) ProtoMessage() {}

func (x *UpdateTechnologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_technology_technology_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTechnologyRequest.ProtoReflect.Descriptor instead.
func (*UpdateTechnologyRequest) Descriptor() ([]byte, []int) {
	return file_technology_technology_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTechnologyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTechnologyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTechnologyRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateTechnologyRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UpdateTechnologyRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *UpdateTechnologyRequest) GetOfficialUrl() string {
	if x != nil {
		return x.OfficialUrl
	}
	return ""
}

func (x *UpdateTechnologyRequest) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

type UpdateTechnologyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Technology    *Technology            `protobuf:"bytes,1,opt,name=technology,proto3" json:"technology,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTechnologyResponse) Reset() {
	*x = UpdateTechnologyResponse{}
	mi := &file_technology_technology_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTechnologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTechnologyResponse) ProtoMessage() {}

func (x *UpdateTechnologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_technology_technology_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTechnologyResponse.ProtoReflect.Descriptor instead.
func (*UpdateTechnologyResponse) Descriptor() ([]byte, []int) {
	return file_technology_technology_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTechnologyResponse) GetTechnology() *Technology {
	if x != nil {
		return x.Technology
	}
	return nil
}

type DeleteTechnologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTechnologyRequest) Reset() {
	*x = DeleteTechnologyRequest{}
	mi := &file_technology_technology_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTechnologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTechnologyRequest) ProtoMessage() {}

func (x *DeleteTechnologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_technology_technology_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTechnologyRequest.ProtoReflect.Descriptor instead.
func (*DeleteTechnologyRequest) Descriptor() ([]byte, []int) {
	return file_technology_technology_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTechnologyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTechnologyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTechnologyResponse) Reset() {
	*x = DeleteTechnologyResponse{}
	mi := &file_technology_technology_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTechnologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTechnologyResponse) ProtoMessage() {}

func (x *DeleteTechnologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_technology_technology_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTechnologyResponse.ProtoReflect.Descriptor instead.
func (*DeleteTechnologyResponse) Descriptor() ([]byte, []int) {
	return file_technology_technology_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTechnologyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_technology_technology_service_proto protoreflect.FileDescriptor

const file_technology_technology_service_proto_rawDesc = "" +
	"\n" +
	"#technology/technology_service.proto\x12\n" +
	"technology\x1a\x1btechnology/technology.proto\"C\n" +
	"\x17ListTechnologiesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"l\n" +
	"\x18ListTechnologiesResponse\x12:\n" +
	"\ftechnologies\x18\x01 \x03(\v2\x16.technology.TechnologyR\ftechnologies\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"&\n" +
	"\x14GetTechnologyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x15GetTechnologyResponse\x126\n" +
	"\n" +
	"technology\x18\x01 \x01(\v2\x16.technology.TechnologyR\n" +
	"technology\"\xaa\x01\n" +
	"\x17CreateTechnologyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12!\n" +
	"\fofficial_url\x18\x05 \x01(\tR\vofficialUrl\x12\x12\n" +
	"\x04logo\x18\x06 \x01(\tR\x04logo\"R\n" +
	"\x18CreateTechnologyResponse\x126\n" +
	"\n" +
	"technology\x18\x01 \x01(\v2\x16.technology.TechnologyR\n" +
	"technology\"\xba\x01\n" +
	"\x17UpdateTechnologyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\x12!\n" +
	"\fofficial_url\x18\x06 \x01(\tR\vofficialUrl\x12\x12\n" +
	"\x04logo\x18\a \x01(\tR\x04logo\"R\n" +
	"\x18UpdateTechnologyResponse\x126\n" +
	"\n" +
	"technology\x18\x01 \x01(\v2\x16.technology.TechnologyR\n" +
	"technology\")\n" +
	"\x17DeleteTechnologyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x18DeleteTechnologyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe5\x03\n" +
	"\x11TechnologyService\x12]\n" +
	"\x10ListTechnologies\x12#.technology.ListTechnologiesRequest\x1a$.technology.ListTechnologiesResponse\x12T\n" +
	"\rGetTechnology\x12 .technology.GetTechnologyRequest\x1a!.technology.GetTechnologyResponse\x12]\n" +
	"\x10CreateTechnology\x12#.technology.CreateTechnologyRequest\x1a$.technology.CreateTechnologyResponse\x12]\n" +
	"\x10UpdateTechnology\x12#.technology.UpdateTechnologyRequest\x1a$.technology.UpdateTechnologyResponse\x12]\n" +
	"\x10DeleteTechnology\x12#.technology.DeleteTechnologyRequest\x1a$.technology.DeleteTechnologyResponseB\x1fZ\x1dportfolio-ai/proto/technologyb\x06proto3"

var (
	file_technology_technology_service_proto_rawDescOnce sync.Once
	file_technology_technology_service_proto_rawDescData []byte
)

func file_technology_technology_service_proto_rawDescGZIP() []byte {
	file_technology_technology_service_proto_rawDescOnce.Do(func() {
		file_technology_technology_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_technology_technology_service_proto_rawDesc), len(file_technology_technology_service_proto_rawDesc)))
	})
	return file_technology_technology_service_proto_rawDescData
}

var file_technology_technology_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_technology_technology_service_proto_goTypes = []any{
	(*ListTechnologiesRequest)(nil),  // 0: technology.ListTechnologiesRequest
	(*ListTechnologiesResponse)(nil), // 1: technology.ListTechnologiesResponse
	(*GetTechnologyRequest)(nil),     // 2: technology.GetTechnologyRequest
	(*GetTechnologyResponse)(nil),    // 3: technology.GetTechnologyResponse
	(*CreateTechnologyRequest)(nil),  // 4: technology.CreateTechnologyRequest
	(*CreateTechnologyResponse)(nil), // 5: technology.CreateTechnologyResponse
	(*UpdateTechnologyRequest)(nil),  // 6: technology.UpdateTechnologyRequest
	(*UpdateTechnologyResponse)(nil), // 7: technology.UpdateTechnologyResponse
	(*DeleteTechnologyRequest)(nil),  // 8: technology.DeleteTechnologyRequest
	(*DeleteTechnologyResponse)(nil), // 9: technology.DeleteTechnologyResponse
	(*Technology)(nil),               // 10: technology.Technology
}
var file_technology_technology_service_proto_depIdxs = []int32{
	10, // 0: technology.ListTechnologiesResponse.technologies:type_name -> technology.Technology
	10, // 1: technology.GetTechnologyResponse.technology:type_name -> technology.Technology
	10, // 2: technology.CreateTechnologyResponse.technology:type_name -> technology.Technology
	10, // 3: technology.UpdateTechnologyResponse.technology:type_name -> technology.Technology
	0,  // 4: technology.TechnologyService.ListTechnologies:input_type -> technology.ListTechnologiesRequest
	2,  // 5: technology.TechnologyService.GetTechnology:input_type -> technology.GetTechnologyRequest
	4,  // 6: technology.TechnologyService.CreateTechnology:input_type -> technology.CreateTechnologyRequest
	6,  // 7: technology.TechnologyService.UpdateTechnology:input_type -> technology.UpdateTechnologyRequest
	8,  // 8: technology.TechnologyService.DeleteTechnology:input_type -> technology.DeleteTechnologyRequest
	1,  // 9: technology.TechnologyService.ListTechnologies:output_type -> technology.ListTechnologiesResponse
	3,  // 10: technology.TechnologyService.GetTechnology:output_type -> technology.GetTechnologyResponse
	5,  // 11: technology.TechnologyService.CreateTechnology:output_type -> technology.CreateTechnologyResponse
	7,  // 12: technology.TechnologyService.UpdateTechnology:output_type -> technology.UpdateTechnologyResponse
	9,  // 13: technology.TechnologyService.DeleteTechnology:output_type -> technology.DeleteTechnologyResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_technology_technology_service_proto_init() }
func file_technology_technology_service_proto_init() {
	if File_technology_technology_service_proto != nil {
		return
	}
	file_technology_technology_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_technology_technology_service_proto_rawDesc), len(file_technology_technology_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_technology_technology_service_proto_goTypes,
		DependencyIndexes: file_technology_technology_service_proto_depIdxs,
		MessageInfos:      file_technology_technology_service_proto_msgTypes,
	}.Build()
	File_technology_technology_service_proto = out.File
	file_technology_technology_service_proto_goTypes = nil
	file_technology_technology_service_proto_depIdxs = nil
}
