// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: technology/technology.proto

package technology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Technology struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	OfficialUrl   string                 `protobuf:"bytes,6,opt,name=official_url,json=officialUrl,proto3" json:"official_url,omitempty"`
	Logo          string                 `protobuf:"bytes,7,opt,name=logo,proto3" json:"logo,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Technology) Reset() {
	*x = Technology{}
	mi := &file_technology_technology_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Technology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Technology) ProtoMessage() {}

func (x *Technology) ProtoReflect() protoreflect.Message {
	mi := &file_technology_technology_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Technology.ProtoReflect.Descriptor instead.
func (*Technology) Descriptor() ([]byte, []int) {
	return file_technology_technology_proto_rawDescGZIP(), []int{0}
}

func (x *Technology) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Technology) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Technology) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Technology) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Technology) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Technology) GetOfficialUrl() string {
	if x != nil {
		return x.OfficialUrl
	}
	return ""
}

func (x *Technology) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *Technology) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_technology_technology_proto protoreflect.FileDescriptor

const file_technology_technology_proto_rawDesc = "" +
	"\n" +
	"\x1btechnology/technology.proto\x12\n" +
	"technology\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x01\n" +
	"\n" +
	"Technology\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\x12!\n" +
	"\fofficial_url\x18\x06 \x01(\tR\vofficialUrl\x12\x12\n" +
	"\x04logo\x18\a \x01(\tR\x04logo\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x1fZ\x1dportfolio-ai/proto/technologyb\x06proto3"

var (
	file_technology_technology_proto_rawDescOnce sync.Once
	file_technology_technology_proto_rawDescData []byte
)

func file_technology_technology_proto_rawDescGZIP() []byte {
	file_technology_technology_proto_rawDescOnce.Do(func() {
		file_technology_technology_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_technology_technology_proto_rawDesc), len(file_technology_technology_proto_rawDesc)))
	})
	return file_technology_technology_proto_rawDescData
}

var file_technology_technology_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_technology_technology_proto_goTypes = []any{
	(*Technology)(nil),            // 0: technology.Technology
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_technology_technology_proto_depIdxs = []int32{
	1, // 0: technology.Technology.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_technology_technology_proto_init() }
func file_technology_technology_proto_init() {
	if File_technology_technology_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_technology_technology_proto_rawDesc), len(file_technology_technology_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_technology_technology_proto_goTypes,
		DependencyIndexes: file_technology_technology_proto_depIdxs,
		MessageInfos:      file_technology_technology_proto_msgTypes,
	}.Build()
	File_technology_technology_proto = out.File
	file_technology_technology_proto_goTypes = nil
	file_technology_technology_proto_depIdxs = nil
}
