// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: technology/technology_service.proto

package technology

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TechnologyService_ListTechnologies_FullMethodName = "/technology.TechnologyService/ListTechnologies"
	TechnologyService_GetTechnology_FullMethodName    = "/technology.TechnologyService/GetTechnology"
	TechnologyService_CreateTechnology_FullMethodName = "/technology.TechnologyService/CreateTechnology"
	TechnologyService_UpdateTechnology_FullMethodName = "/technology.TechnologyService/UpdateTechnology"
	TechnologyService_DeleteTechnology_FullMethodName = "/technology.TechnologyService/DeleteTechnology"
)

// TechnologyServiceClient is the client API for TechnologyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TechnologyServiceClient interface {
	ListTechnologies(ctx context.Context, in *ListTechnologiesRequest, opts ...grpc.CallOption) (*ListTechnologiesResponse, error)
	GetTechnology(ctx context.Context, in *GetTechnologyRequest, opts ...grpc.CallOption) (*GetTechnologyResponse, error)
	CreateTechnology(ctx context.Context, in *CreateTechnologyRequest, opts ...grpc.CallOption) (*CreateTechnologyResponse, error)
	UpdateTechnology(ctx context.Context, in *UpdateTechnologyRequest, opts ...grpc.CallOption) (*UpdateTechnologyResponse, error)
	DeleteTechnology(ctx context.Context, in *DeleteTechnologyRequest, opts ...grpc.CallOption) (*DeleteTechnologyResponse, error)
}

type technologyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTechnologyServiceClient(cc grpc.ClientConnInterface) TechnologyServiceClient {
	return &technologyServiceClient{cc}
}

func (c *technologyServiceClient) ListTechnologies(ctx context.Context, in *ListTechnologiesRequest, opts ...grpc.CallOption) (*ListTechnologiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTechnologiesResponse)
	err := c.cc.Invoke(ctx, TechnologyService_ListTechnologies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *technologyServiceClient) GetTechnology(ctx context.Context, in *GetTechnologyRequest, opts ...grpc.CallOption) (*GetTechnologyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTechnologyResponse)
	err := c.cc.Invoke(ctx, TechnologyService_GetTechnology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *technologyServiceClient) CreateTechnology(ctx context.Context, in *CreateTechnologyRequest, opts ...grpc.CallOption) (*CreateTechnologyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTechnologyResponse)
	err := c.cc.Invoke(ctx, TechnologyService_CreateTechnology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *technologyServiceClient) UpdateTechnology(ctx context.Context, in *UpdateTechnologyRequest, opts ...grpc.CallOption) (*UpdateTechnologyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTechnologyResponse)
	err := c.cc.Invoke(ctx, TechnologyService_UpdateTechnology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *technologyServiceClient) DeleteTechnology(ctx context.Context, in *DeleteTechnologyRequest, opts ...grpc.CallOption) (*DeleteTechnologyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTechnologyResponse)
	err := c.cc.Invoke(ctx, TechnologyService_DeleteTechnology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TechnologyServiceServer is the server API for TechnologyService service.
// All implementations must embed UnimplementedTechnologyServiceServer
// for forward compatibility.
type TechnologyServiceServer interface {
	ListTechnologies(context.Context, *ListTechnologiesRequest) (*ListTechnologiesResponse, error)
	GetTechnology(context.Context, *GetTechnologyRequest) (*GetTechnologyResponse, error)
	CreateTechnology(context.Context, *CreateTechnologyRequest) (*CreateTechnologyResponse, error)
	UpdateTechnology(context.Context, *UpdateTechnologyRequest) (*UpdateTechnologyResponse, error)
	DeleteTechnology(context.Context, *DeleteTechnologyRequest) (*DeleteTechnologyResponse, error)
	mustEmbedUnimplementedTechnologyServiceServer()
}

// UnimplementedTechnologyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTechnologyServiceServer struct{}

func (UnimplementedTechnologyServiceServer) ListTechnologies(context.Context, *ListTechnologiesRequest) (*ListTechnologiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTechnologies not implemented")
}
func (UnimplementedTechnologyServiceServer) GetTechnology(context.Context, *GetTechnologyRequest) (*GetTechnologyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTechnology not implemented")
}
func (UnimplementedTechnologyServiceServer) CreateTechnology(context.Context, *CreateTechnologyRequest) (*CreateTechnologyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTechnology not implemented")
}
func (UnimplementedTechnologyServiceServer) UpdateTechnology(context.Context, *UpdateTechnologyRequest) (*UpdateTechnologyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTechnology not implemented")
}
func (UnimplementedTechnologyServiceServer) DeleteTechnology(context.Context, *DeleteTechnologyRequest) (*DeleteTechnologyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTechnology not implemented")
}
func (UnimplementedTechnologyServiceServer) mustEmbedUnimplementedTechnologyServiceServer() {}
func (UnimplementedTechnologyServiceServer) testEmbeddedByValue()                           {}

// UnsafeTechnologyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TechnologyServiceServer will
// result in compilation errors.
type UnsafeTechnologyServiceServer interface {
	mustEmbedUnimplementedTechnologyServiceServer()
}

func RegisterTechnologyServiceServer(s grpc.ServiceRegistrar, srv TechnologyServiceServer) {
	// If the following call panics, it indicates UnimplementedTechnologyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TechnologyService_ServiceDesc, srv)
}

func _TechnologyService_ListTechnologies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTechnologiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechnologyServiceServer).ListTechnologies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TechnologyService_ListTechnologies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechnologyServiceServer).ListTechnologies(ctx, req.(*ListTechnologiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TechnologyService_GetTechnology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTechnologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechnologyServiceServer).GetTechnology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TechnologyService_GetTechnology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechnologyServiceServer).GetTechnology(ctx, req.(*GetTechnologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TechnologyService_CreateTechnology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTechnologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechnologyServiceServer).CreateTechnology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TechnologyService_CreateTechnology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechnologyServiceServer).CreateTechnology(ctx, req.(*CreateTechnologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TechnologyService_UpdateTechnology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTechnologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechnologyServiceServer).UpdateTechnology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TechnologyService_UpdateTechnology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechnologyServiceServer).UpdateTechnology(ctx, req.(*UpdateTechnologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TechnologyService_DeleteTechnology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTechnologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechnologyServiceServer).DeleteTechnology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TechnologyService_DeleteTechnology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechnologyServiceServer).DeleteTechnology(ctx, req.(*DeleteTechnologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TechnologyService_ServiceDesc is the grpc.ServiceDesc for TechnologyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TechnologyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "technology.TechnologyService",
	HandlerType: (*TechnologyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTechnologies",
			Handler:    _TechnologyService_ListTechnologies_Handler,
		},
		{
			MethodName: "GetTechnology",
			Handler:    _TechnologyService_GetTechnology_Handler,
		},
		{
			MethodName: "CreateTechnology",
			Handler:    _TechnologyService_CreateTechnology_Handler,
		},
		{
			MethodName: "UpdateTechnology",
			Handler:    _TechnologyService_UpdateTechnology_Handler,
		},
		{
			MethodName: "DeleteTechnology",
			Handler:    _TechnologyService_DeleteTechnology_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "technology/technology_service.proto",
}
